//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_work1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_info_view
    {
        public int Id { get; set; }
        public string 客戶名稱 { get; set; }
        public Nullable<int> contact_count { get; set; }
        public Nullable<int> bank_count { get; set; }
    }
}
